name: Deploy to production
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v4

      - name: Use Node.js 21
        uses: actions/setup-node@v4
        with:
          node-version: '21'
      - name: Build project
        run: |
          npm install
          npm run build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ vars.PROD_FTP_HOST }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./public/build/
          server-dir: ./public/build/
          #dry-run: true
